export const ACTIONS = {
  SET_ALL_CATEGORIES: "SET_ALL_CATEGORIES",
  SET_IS_LOADING: "SET_IS_LOADING",
  SET_ERROR: "SET_ERROR",
  SET_LIKED_RECIPE: "SET_LIKED_RECIPE",
  SET_SAVE_RECIPE: "SET_SAVE_RECIPE",
  SET_SELECTED_CATEGORY: "SET_SELECTED_CATEGORY",
  SET_SHOP_ITEM: "SET_SHOP_ITEM",
  SET_LOCAL_ITEM: "SET_LOCAL_ITEM",
};
