export const ACTIONS = {
  SET_ALL_CATEGORIES: "SET_ALL_CATEGORIES",
  SET_IS_LOADING: "SET_IS_LOADING",
  SET_ERROR: "SET_ERROR",
  SET_LIKED_RECIPE: "SET_LIKED_RECIPE",
  SET_SAVE_RECIPE: "SET_SAVE_RECIPE",
  SET_SELECTED_CATEGORY: "SET_SELECTED_CATEGORY",
  SET_SHOP_ITEMS: "SET_SHOP_ITEMS",
  SET_LOCAL_ITEMS: "SET_LOCAL_ITEMS",
  SET_SHOW_LOAD_MORE: "SET_SHOW_LOAD_MORE",
  SET_PAGE: "SET_PAGE",
  SET_RECIPE: "SET_RECIPE",
  SET_TOTAL_PRICE: "SET_TOTAL_PRICE",
};
